---
name: Build Binaries

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.rs'
      - '**/build_binaries.yml'

jobs:
  linux:
    runs-on: ubuntu-latest
    # needs: release
    steps:
      - uses: actions/checkout@v3
      - run: cargo build -r
      - run: ls -la target/release
      - uses: actions/upload-artifact@v3
        with:
          name: weather
          path: target/release/weather
